backend:
  name: github
  repo: isacopraxolu-terramedia/terramediaproject
  branch: main
  auth_type: implicit
  app_id: Ov23liBfEto5djWoQzA5

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "artists"
    label: "Artists"
    folder: "content/artists"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "body", widget: "markdown" }
      - { label: "Immagine", name: "image", widget: "image" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages.json"
        label: "Contenuti del sito"
        name: "site_pages"
        fields:
          - { label: "Homepage – Titolo", name: "home_title", widget: "string" }
          - { label: "Homepage – Sottotitolo", name: "home_subtitle", widget: "text" }
