backend:
  name: github
  repo: isacopraxolu-terramedia/terramediaproject
  branch: main
  base_url: https://terramediaproject.it
  auth_endpoint: /api/auth

media_folder: "terramedia-site/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    folder: "terramedia-site/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Corpo", name: "body", widget: "markdown"}
