backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pagine"
    file: "content/pages.json"
    format: "json"
    fields:
      - label: "Home"
        name: "home"
        widget: "object"
        fields:
          - { label: "Titolo", name: "headline", widget: "string" }
          - { label: "Sottotitolo", name: "subhead", widget: "text" }
      - label: "Chi siamo"
        name: "about"
        widget: "object"
        fields:
          - { label: "Paragrafo 1", name: "text1", widget: "text" }
          - { label: "Paragrafo 2", name: "text2", widget: "text" }
      - label: "Contatti"
        name: "contacts"
        widget: "object"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Telefono", name: "phone", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }

